[build]
  command = "npm run build"
  publish = "dist"
  functions = "supabase/functions"

[functions]
  external_node_modules = ["twilio"]
  node_bundler = "esbuild"

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*", Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization"}

[[redirects]]
  from = "/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*", Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization"}

[[redirects]]
  from = "/webhook/whatsapp"
  to = "/.netlify/functions/whatsapp/webhook"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*", Access-Control-Allow-Headers = "*"}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
